export const themen = [
  {
    name: "Tiere",
    words: [
      "Elefant",
      "Kanguroo",
      "Gecko",
      "Pferd",
      "Biene",
      "Schäferhund",
      "Tiger",
      "Python",
      "Kalmar",
      "Boa",
      "Zwergfalke",
      "Alpensteinbock",
      "Atlasfalter",
      "Axolotl",
      "Feuersalamander",
      "Kröte",
      "Australische Hüpfmaus",
      "Blauer Pfau",
      "Ameise",
      "Bartagame",
      "Blattschneiderameise",
      "Jaguar",
      "Vogelspinne",
      "Baikalente",
      "Blauer Morpho",
      "Bonobo",
      "Buntwaran",
      "Dorcasgazelle",
      "Ceylon-Lanzenotter",
      "Erdmännchen",
      "Emu",
      "Fennek",
      "Goldkopf-Löwenäffchen",
      "Großer Ameisenbär",
      "Pfeilgiftfrosch",
      "Ameise",
      "Ameisenbär",
      "Biene",
      "Blattlaus",
      "Blutegel",
      "Fauchschabe",
      "Florfliege",
      "Flusskrebs",
      "Geißelspinne",
      "Gelbrandkäfer",
      "Gespenstschrecke",
      "Gestreifter Rosenkäfer",
      "Gottesanbeterin",
      "Hornisse",
      "Hummer",
      "Kartoffelkäfer",
      "Köcherfliege",
      "Kreuzspinne",
      "Europäische Languste",
      "Maikäfer",
      "Marienkäfer",
      "Pfeilschwanzkrebs",
      "Heiliger Pillendreher",
      "Regenwurm",
      "Uhu",
      "Schmetterling",
      "Wattwurm",
      "Aguti",
      "Akazienratte",
      "Alpaka",
      "Biber",
      "Braunbär",
      "Chinchilla",
      "Dachs",
      "Delphin",
      "Eichhörnchen",
      "Eisbär",
      "Esel",
      "Faultier",
      "Flughund",
      "Flusspferd",
      "Frettchen",
      "Fuchs",
    ],
  },
  {
    name: "Autos",
    words: [
      "BMW",
      "Porsche",
      "Mercedes",
      "Audi",
      "Chevrolet",
      "Daihatsu",
      "Suzuki",
      "Honda",
      "Hyundai",
      "Abarth",
      "Academy",
      "Ackerman",
      "Adams",
      "Renault",
      "Citroen",
      "Peugeot",
      "Dacia",
      "Skoda",
      "Alfa Romeo",
      "Amphicar",
      "Ford",
      "Bentley",
      "Bitter",
      "Borgward",
      "Brabham",
      "Brabus",
      "Pontiac",
      "Ganzhong",
      "General Motors",
      "Gemballa",
      "Hainan",
      "Hanomag",
      "Moskwitsch",
      "Nanjing Soyat",
      "Opel",
      "Oldsmobile",
      "Pittsburgh",
      "Plymouth",
      "Polestar",
      "Pullman",
      "Ranger",
      "Rolls-Royce",
      "Saab",
      "Samsung",
      "Fiat",
      "Triumph",
      "Talbot",
      "Tarantula",
      "Tatra",
      "Toyota",
      "Trabant",
      "Wartburg",
      "Vauxhall",
      "Yamaha",
      "Nissan",
      "Maserati",
      "Chrysler",
      "Lancia",
    ],
  },
  {
    name: "Länder",
    words: [
      "Deutschland",
      "China",
      "Togo",
      "Frankreich",
      "Schottland",
      "Kanada",
      "Norwegen",
      "Finnland",
      "Dänemark",
      "Uruguay",
      "Brasilien",
      "Argentinien",
      "Honduras",
      "Ägypten",
      "Tunesien",
      "Marokko",
      "Abchasien",
      "Chile",
      "Burundi",
      "Dominica",
      "Dominikanische Republik",
      "Elfenbeinküste",
      "Indien",
      "Pakistan",
      "Irak",
      "Kasachstan",
      "Kirgistan",
      "Kuba",
      "Lettland",
      "Litauen",
      "Marshallinseln",
      "Mauritus",
      "Nauru",
      "Nordmazedonien",
      "Österreich",
      "Oman",
      "Indonesien",
      "Palau",
      "Paraguay",
      "Polen",
      "Saudi-Arabien",
      "Schweiz",
      "Thailand",
      "Türkei",
      "Venezuela",
      "Vereinigte Arabische Emirate",
      "Zypern",
      "Zentralafrikanische Republik",
      "Albanien",
      "Angola",
      "Bhutan",
      "Botswana",
      "Cookinseln",
      "Costa Rica",
      "Eritrea",
      "Ecuador",
      "Fidschi",
      "Ghana",
      "Griechenbland",
      "Honduras",
      "Haiti",
      "Iran",
      "Italien",
      "Spanien",
      "Portugal",
      "Island",
      "Schweden",
      "Israel",
      "Ukraine",
      "Kasachstan",
      "Komoren",
      "Mali",
      "Malta",
      "Nicaragua",
      "Osttimor",
      "Oman",
      "Russland",
      "Salomonen",
      "Sambia",
      "Togo",
      "Tonga",
      "Usbekistan",
      "Vatikanstadt",
      "Vanuatu",
      "Afghanistan",
      "Australien",
      "Belize",
      "Benin",
      "Burkina Faso",
      "El Salvador",
      "Estland",
      "Gambia",
      "Jamaika",
      "Jordanien",
      "Kambodscha",
      "Kirbati",
      "Lesotho",
      "Liechtenstein",
      "Madagaskar",
      "Malawi",
      "Nepal",
      "Nicaragua",
      "Neuseeland",
      "Philippinen",
      "Peru",
      "Samoa",
      "San Marino",
      "Senegal",
      "Tansania",
      "Uruguay",
      "Vereingte Staaten von Amerika",
    ],
  },
  {
    name: "Obst",
    words: [
      "Apfel",
      "Banane",
      "Birne",
      "Pflaume",
      "Himbeere",
      "Erdbeere",
      "Kiwi",
      "Stachelbeere",
      "Zitrone",
      "Limone",
      "Orange",
      "Apfelsine",
      "Kumquat",
      "Quitte",
      "Elsbeere",
      "Mispel",
      "Vogelbeere",
      "Aprikose",
      "Kirsche",
      "Mirabelle",
      "Grapefruit",
      "Pampelmuse",
    ],
  },
  {
    name: "Beruf",
    words: [
      "Programmierer",
      "Web Developer",
      "Arzt",
      "Technischer Zeichner",
      "Modellbauer",
      "Mechatroniker",
      "Automobilkaufmann",
      "Bürokaufmann",
      "Immobilienkaufmann",
      "Justizfachangestellter",
      "Notarfachangestellter",
      "Patentanwaltsfachangestellter",
      "Steuerfachangestellter",
      "Reiseverkehrskaufmann",
      "Fachkraft für Postdienstleistungen",
      "Luftverkehrskaufmann",
      "Schifffahrtskaufmann",
      "Berufskraftfahrer",
      "Hafenschiffer",
      "Aufbereitungsmechaniker",
      "Büchsenmacher",
      "Graveur",
      "Galvaniseur",
      "Feinwerkmechaniker",
      "Schleifer",
    ],
  },
];
